### ISSUE TITLE
RFC for Client Design

### ISSUE THREAD

**Issue by gabcbrown** [Manta-Network/manta-api#1]
Write up RFC with design for Client interface.

**Comment by gabcbrown** [comment]
# RFC: manta-api and subxt client

**Date**: 06/02/21

## Overview/Goals/Motivation
Enable users to interact with the Manta network with either an intuitive locally-running web app or a command line interface. Underlying both of these interfaces is a common api library (manta-api) that provides a simple, reusable interface for zkp generation, submitting extrinsics, etc. Manta-api can be compiled to wasm, surfaced through a rest api, or integrated into a cli.

## Design
### manta-api
**technology**: Rust
**libraries**: manta-types, manta-crypto
**functionality**: 
- stateless typed transaction functionality 
- most important part is zkp gen
- also supports extrinsic submissions
- can also include a light rest api

### JS Client
**technology**: js
**libraries**: Polkadot.js
**functionality**:
- gets wallet keys from Polkadot browser wallet
- presents all transaction options
- runs wasm zkp generation in the browser => compiled from manta-api
    - if wasm isn't ready, can run locally a light rest client wrapper around manta-api
- submits proofs to target node
- stores transaction hashes etc. back in the browser wallet

### Rust subxt client
**technology**: Rust
**libraries**: manta-api, manta-types
**functionality**:
- cli for subxt only
- local account key storage (so you only have to enter once to do transactions)
- initiate transactions with target nodes
- local storage of block/transaction hashes/utxos
- not a 'permanent' or recoverable storage... what happens if e.g. the computer turns off while a transaction is being finalized? or the hard drive fails? can we do account recovery

## Dependencies
There are a couple of dependencies for this work:
* *manta-types:* The client will rely on the manta-types workspace for type definitions. This repository has just been refactored out from other repositories in the Manta project, so there may be some unforseen instability or other refactoring that needs to happen.
* *Polkadot.js client interface* We will need to make sure the `manta-api` design works well for building the `Polkadot.js`-based client. 

## Open questions
- will wasm be fast enough for zkp gen?
- is this design too much duplication with Polkadot.js?
- what order should we prioritize developing these components?

**Comment by stechu** [comment]
would be great to draw a dependency graph to illustrate the dependencies between repos. Also, would be nice to mark each bullet point (`essential` : e.g. done within 1 week, `important`: e.g. done in 2-3 weeks, and `good to have`: e.g. in 1 or 2 months). 

Also, my two cents is that there is a good design cannot be `brain-stormed` from the vacuum. We should figure out the `essential`s and start implementation-refactor iteration.

**Comment by gabcbrown** [comment]
Looking through the code, right now `manta-api` covers:
zkp tools
- circuits: `TransferCircuit`, `ReclaimCircuit`, `impl ConstraintSynthesizer<Fq> for TransferCircuit`, `impl ConstraintSynthesizer<Fq> for ReclaimCircuit`
- gadgets: `sender_token_well_formed_circuit_helper`, ` receiver_token_well_formed_circuit_helper`, `prf_circuit_helper`, `merkle_membership_circuit_proof`
- keys: `write_zkp_keys`, `manta_transfer_zkp_key_gen`, `manta_reclaim_zkp_key_gen`, `TRANSFER_PK`, `RECLAIM_PK`

payload generation
- `generate_mint_payload`, `generate_private_transfer_payload`, `generate_reclaim_payload`

I'm still a bit unclear about the api surfaces that will lie between these clients and `manta-api`. Do we want the highest-level abstraction in `manta-api` to be very simple user inputs e.g. `String`, `Path`, `u64`?, or do we want `manta-api` to only expose functionality that uses `manta-types` e.g. `MantaAsset`, `AssetId`, `MantaAssetPubInfo`? 

A client will at the very least need to call one of the `payload` functions to get the data format to submit extrinsics. Do we currently have any functions to help create the inputs? e.g. `generate_private_transfer_payload` has 
```
	commit_param: CommitmentParam,
	hash_param: HashParam,
	pk: &Groth16Pk,
	sender_1: SenderMetaData,
	sender_2: SenderMetaData,
	receiver_1: MantaAssetProcessedReceiver,
	receiver_2: MantaAssetProcessedReceiver,
	rng: &mut R,
```

**Comment by zhenfeizhang** [comment]
> Do we want the highest-level abstraction in manta-api to be very simple user inputs e.g. String, Path, u64?,

I like this idea. It would be nice to make all the manta `struct`s to be transparent to the caller.
What I am less certain is whether the `serdes` should happen within `manta-subxt` or `manta-api`.
Since `manta-api` is also the interface to `manta-js` and `manta-js` currently does not recognize the `struct`s any way.
I incline to propose that `manta-api` does the `serdes`; and `manta-subxt` communicate with `manta-api` with raw bytes.

**Comment by gabcbrown** [comment]
@zhenfeizhang and I talked more about this offline. Since we want `manta-api` to be stateless, the user will have to pass in a ledger state for operations like building a private transfer proof. Ledger state is a pretty different abstraction level than the string of a public key and address, so the proposed api and location of the new functionality is:

**manta-api**
stateless methods/types for easily creating and serializing transactions on the manta network, all using manta defined types as inputs
- proof construction functions
- -`construct_private_transfer_proof` and `construct_reclaim_proof`
- - zkp keys, rng, pk, ledger state, 2 sender coins, 2 receivers 

- payload generating functions (listed above)
- zkp generating functions (listed above)

**manta-types**
We'll need some utils for constructing manta types so users can do this reliably (and in our own code base we are consistent about the typecasting/constructors) 
- `From` impls for manta types from common Rust types (e.g. String, Vec)

**manta-subxt**
stateful CLI that uses `manta-api` and `manta-types` `From` impls to parse user input, construct transactions, submit to a manta node, and store results. 
- locally storing user-relevant transaction hashes 
- locally storing user account keys
- cli for user interaction with node
- call manta api and manta types to parse and construct transactions

I'm currently working on an mvp for both the [`manta-api`](https://github.com/Manta-Network/manta-api/compare/extrinsics?expand=1) and `manta-subxt` components. 

Something that has come up is that `construct_private_transfer_proof` needs the right types to handle the sharded ledger properly. 
1) The `MantaExtrinsic` trait doesn't expose any sharding logic so it looks like we'll have to use the `Shard` type directly. This will need to be modified to support swap, which contains a list of trading pairs (liquidity pools).
2) MantaExtrinsic` is currently defined in `manta-subxt`, and I've copied it into `manta-api` to get things working which is not ideal. But `Shard` is located in `manta-types`, so I think it will be fine, I was just running into some issues trying not to create circular dependencies so there might be more to untangle here.
